### ISSUE TITLE
Leaks into shell namespace

### ISSUE THREAD

**Issue by AstraLuma** [gforsyth/xonsh-pacman-tabcomplete#3]
All the globals defined in `pacman_tabcomplete.xsh` leak in to `__main__`.

**Comment by gforsyth** [comment]
Whoops.  Ok, I'm going to the movies but I'll fix this later tonight.  Although in the interim, PRs are certainly welcome.

**Comment by gforsyth** [comment]
This is fixed and I've pushed up version 0.1.4 to github and pypi
